name: Trigger Webhook Event

on:
  push:
  pull_request:
    types: [opened, closed]

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to endpoint
        run: |
          curl -X POST https://52a4-2401-4900-3686-a02a-5b2-7228-8452-bb6f.ngrok-free.app
            -H "Content-Type: application/json" \
            -d '{"event_type":"trigger"}'
